/**
Seed Data Loader Script for QSense Application
**/

START TRANSACTION;

USE qsense_db;

/**
Inserting seed data for sub-category in the application
**/
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (12,2,'WALKING_RUNNING_DISTANCE','Walking_distance','Walking Distance','unit_walking_distance','#FFFFFF',12,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (13,2,'SLEEP','Sleeping','Sleeping','unit_sleeping','#FFFFFF',13,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (14,2,'HEART_RATE','Heart_Rate','Heart Rate','unit_heart_rate','#FFFFFF',14,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (15,2,'FLIGHTS_CLIMBED','Flights _Climbed','Flights  Climbed','unit_flights _climbed','#FFFFFF',15,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (16,1,'AMERICAN_FOOTBALL','American_Football','American Football','unit_american_football','#FFFFFF',16,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (17,1,'ARCHERY','Archery','Archery','unit_archery','#FFFFFF',17,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (18,1,'AUSTRALIAN_FOOTBALL','Australian_Football','Australian Football','unit_australian_football','#FFFFFF',18,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (19,1,'BADMINTON','Badminton','Badminton','unit_badminton','#FFFFFF',19,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (20,1,'BASEBALL','Baseball','Baseball','unit_baseball','#FFFFFF',20,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (21,1,'BASKETBALL','Basketball','Basketball','unit_basketball','#FFFFFF',21,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (22,1,'BOWLING','Bowling','Bowling','unit_bowling','#FFFFFF',22,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (23,1,'BOXING','Boxing','Boxing','unit_boxing','#FFFFFF',23,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (24,1,'CLIMBING','Climbing','Climbing','unit_climbing','#FFFFFF',24,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (25,1,'CRICKET','Cricket','Cricket','unit_cricket','#FFFFFF',25,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (26,1,'CROSS_TRAINING','Cross_Training','Cross Training','unit_cross_training','#FFFFFF',26,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (27,1,'CURLING','Curling','Curling','unit_curling','#FFFFFF',27,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (28,1,'DANCE','Dance','Dance','unit_dance','#FFFFFF',28,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (29,1,'DANCE_INSPIRED_TRAINING','Dance_Inspired_Training','Dance Inspired Training','unit_dance_inspired_training','#FFFFFF',29,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (30,1,'ELLIPTICAL','Elliptical','Elliptical','unit_elliptical','#FFFFFF',30,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (31,1,'EQUESTRIAN_SPORTS','Equestrian_Sports','Equestrian Sports','unit_equestrian_sports','#FFFFFF',31,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (32,1,'FENCING','Fencing','Fencing','unit_fencing','#FFFFFF',32,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (33,1,'FISHING','Fishing','Fishing','unit_fishing','#FFFFFF',33,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (34,1,'FUNCTIONAL_STRENGTH_TRAINING','Functional_Strength_Training','Functional Strength Training','unit_functional_strength_training','#FFFFFF',34,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (35,1,'GOLF','Golf','Golf','unit_golf','#FFFFFF',35,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (36,1,'GYMNASTICS','Gymnastics','Gymnastics','unit_gymnastics','#FFFFFF',36,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (37,1,'HANDBALL','Handball','Handball','unit_handball','#FFFFFF',37,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (38,1,'HIKING','Hiking','Hiking','unit_hiking','#FFFFFF',38,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (39,1,'HOCKEY','Hockey','Hockey','unit_hockey','#FFFFFF',39,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (40,1,'HUNTING','Hunting','Hunting','unit_hunting','#FFFFFF',40,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (41,1,'LACROSSE','Lacrosse','Lacrosse','unit_lacrosse','#FFFFFF',41,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (42,1,'MARTIAL_ARTS','Martial_Arts','Martial Arts','unit_martial_arts','#FFFFFF',42,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (43,1,'MIND_AND_BODY','Mind_And_Body','Mind And Body','unit_mind_and_body','#FFFFFF',43,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (44,1,'CARDIO_TRAINING','Cardio_Training','Cardio Training','unit_cardio_training','#FFFFFF',44,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (45,1,'PADDLE_SPORTS','Paddle_Sports','Paddle Sports','unit_paddle_sports','#FFFFFF',45,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (46,1,'PLAY','Play','Play','unit_play','#FFFFFF',46,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (47,1,'PREPARATION_AND_RECOVERY','Preparation_And_Recovery','Preparation And Recovery','unit_preparation_and_recovery','#FFFFFF',47,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (48,1,'RACQUETBALL','Racquetball','Racquetball','unit_racquetball','#FFFFFF',48,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (49,1,'ROWING','Rowing','Rowing','unit_rowing','#FFFFFF',49,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (50,1,'RUGBY','Rugby','Rugby','unit_rugby','#FFFFFF',50,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (51,1,'SAILING','Sailing','Sailing','unit_sailing','#FFFFFF',51,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (52,1,'SKATING_SPORTS','Skating_Sports','Skating Sports','unit_skating_sports','#FFFFFF',52,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (53,1,'SNOW_SPORTS','Snow_Sports','Snow Sports','unit_snow_sports','#FFFFFF',53,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (54,1,'SOCCER','Soccer','Soccer','unit_soccer','#FFFFFF',54,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (55,1,'SOFTBALL','Softball','Softball','unit_softball','#FFFFFF',55,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (56,1,'SQUASH','Squash','Squash','unit_squash','#FFFFFF',56,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (57,1,'STAIR_CLIMBING','Stair_Climbing','Stair Climbing','unit_stair_climbing','#FFFFFF',57,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (58,1,'SURFING_SPORTS','Surfing_Sports','Surfing Sports','unit_surfing_sports','#FFFFFF',58,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (59,1,'SWIMMING','Swimming','Swimming','unit_swimming','#FFFFFF',59,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (60,1,'TABLE_TENNIS','Table_Tennis','Table Tennis','unit_table_tennis','#FFFFFF',60,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (61,1,'TENNIS','Tennis','Tennis','unit_tennis','#FFFFFF',61,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (62,1,'TRACK_AND_FIELD','Track_And_Field','Track And Field','unit_track_and_field','#FFFFFF',62,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (63,1,'TRADITIONAL_STRENGTH_TRAINING','Traditional_Strength_Training','Traditional Strength Training','unit_traditional_strength_training','#FFFFFF',63,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (64,1,'VOLLEYBALL','Volleyball','Volleyball','unit_volleyball','#FFFFFF',64,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (65,1,'WATER_FITNESS','Water_Fitness','Water Fitness','unit_water_fitness','#FFFFFF',65,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (66,1,'WATER_POLO','Water_Polo','Water Polo','unit_water_polo','#FFFFFF',66,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (67,1,'WATER_SPORTS','Water_Sports','Water Sports','unit_water_sports','#FFFFFF',67,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (68,1,'WRESTLING','Wrestling','Wrestling','unit_wrestling','#FFFFFF',68,false,false);
INSERT INTO `sub_category` (`id`,`category_id`,`name`,`description`,`display_name`,`units`,`color`,`sort_order`,`is_dashboard_visible`,`is_leaderboard_visible`) VALUES (69,1,'YOGA','Yoga','Yoga','unit_yoga','#FFFFFF',69,false,false);

COMMIT;
